### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by grigio** [apendua/require#1]
Hi, I tried to install this package via mrt but it seems it doesn't work. (`mrt add define`)

Is possible to use this package also for require asynchronously external libs like Google Maps?
https://github.com/millermedeiros/requirejs-plugins

Thanks

**Comment by apendua** [comment]
@grigio Thank you for this report. Could you provide more details on this error (maybe some logs)? I've tested the package on my desktop several times and it seams to work fine.

The answer to you question is unfortuantelly "no". This is not what this library is designed for. It only works with local source code and it helps to execute fragments of your code in the right order. My goal was not to rewrite `requirejs` but rather provide a very simple implementation of it's key features.

So if you want to load external code dynamically, please use the original `requirejs` or refer to my other project [module-loader](https://github.com/apendua/module-loader), which I think may be exactlly what you're looking for ;)

**Comment by grigio** [comment]
Thanks for the reply, I have no useful error I thought it was a meteorite package.
I tried a bit bower/requirejs/grunt/tests and I like the workflow, but with meteor many packages aren't npm or requirejs  -like so I still have to find a way to integrate all the pieces which satisfy me

**Comment by apendua** [comment]
@grigio Well, `define` is a meteorite package, so `mrt add define` should work :)

**Comment by grigio** [comment]
Ok I tried it again and I see "✓ define" so It finds the package now.
How would you use "module-loader" to load Google Analytics Asynchronously (https://developers.google.com/analytics/devguides/collection/gajs/) ?

**Comment by apendua** [comment]
@grigio I guess, I would probbably do something like this:

``` javascript
var _gaq = _gaq || [], gaq = null;
ModuleLoader.define("google-analytics", {
  source: ('https:' == document.location.protocol ? 'https://ssl' : 'http://www')
      + '.google-analytics.com/ga.js';,
  verify: function () { return gaq },
  loaded: function () { gaq = _gaq },
});
ModuleLoader.require("google-analytics");
```

It doesn't look very elegant though, since the `verify` routine was planned to find some global object that the loaded module would provide. However, `google-analytics` does not seem to define any global objects, it rather works with the `_gaq` that you need to define manually. That's why we need the second helper object, and I need to admit that I don't like it :/

**Comment by grigio** [comment]
Thanks I'll look at your code
