### ISSUE TITLE
If modules are already defined, should an error be thrown

### ISSUE THREAD

**Issue by mitar** [apendua/require#10]
Currently an error is thrown if modules are already defined. I think this is a bit too much. What about replacing it with just a warning, like: https://github.com/peerlibrary/require/commit/c419a4e4af06259000458ad2e26a7d11dfd428a0

**Comment by apendua** [comment]
Makes sense to me, can you create a PR?

**Comment by mitar** [comment]
After some more experience we disabled even a warning, because it makes no sense to put warnings in production into user's console. This should really be a warning while developing. What do you think?

**Comment by apendua** [comment]
You are right, but then we would need to have some config to let the user turn the option on and off, which is of course doable, but it requires a lot more consideration. I would go with a warning for know, and in the future we can allow user to disable it.
