### ISSUE TITLE
Move dependencies to function declaration

### ISSUE THREAD

**Issue by christianbundy** [apendua/require#12]
What do you think of changing this:

``` js
require('superCoolModule', function (superCoolModule) {
  superCoolModule.sayHi();
});
```

to this:

``` js
require(function (superCoolModule) {
  superCoolModule.sayHi();
});
```

We could easily [grab the names of the function's arguments](http://stackoverflow.com/a/9924463/3236521) and reduce the redundancy when defining a function, without making any changes to this way of requiring:

``` js
require('superCoolModule').sayHi();
```

**Comment by apendua** [comment]
@christianbundy :+1: 

Please create a PR againts `devel` branch.
