### ISSUE TITLE
Possible incompatibility with ES6/Traceur

### ISSUE THREAD

**Issue by christianbundy** [apendua/require#14]
~~You can see the details at mquandalle/meteor-harmony#4, but I wanted to let you know that there's an incompatibility between the `require` package and [google/traceur-compiler](/google/traceur-compiler), which _may_ be a namespacing problem.~~

The problem had to do with Node's `module.exports` which doesn't exist in Meteor, and has nothing to do with this package. Thanks!

**Comment by apendua** [comment]
@christianbundy That relieves me, thank you for the update :)
